// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grupwvkohvwniiqvzahk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydXB3dmtvaHZ3bmlpcXZ6YWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODEwMjcsImV4cCI6MjA2MjM1NzAyN30.0pggcz4h4vkdyZva_j5ce6633kxce08MjWrO74ptmyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);